apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadsim
  template:
    metadata:
      labels:
        app: loadsim
    spec:
      containers:
      - name: loadsim
        image: 122315765326.dkr.ecr.us-east-1.amazonaws.com/loadsim:loadsim
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
                name: pod-secret
                key: ENVIRONMENT

        

---
apiVersion: v1
kind: Service
metadata:
  name: loadsim-service
spec:
  selector:
    app: loadsim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

  



  
  